spring.application.name=projeto1

spring.profiles.active=${APP_PROFILE:test}

spring.jpa.open-in-view=false

security.client-id=${CLIENT_ID:projeto1id}
security.client-secret=${CLIENT_SECRET:projeto1secret}

security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://127.0.0.1:5173,http://localhost:5173}